sequenceDiagram
     participant Rep. User(GitHub)
     participant Git(local)
     participant pg_landmetrics

		activate Rep. User(GitHub)
   opt not updated
	Git(local) ->> Rep. User(GitHub): check changes
		activate Git(local)
	Rep. User(GitHub)-->> Git(local): latest version
		deactivate Rep. User(GitHub)
   end

   Git(local) ->> pg_landmetrics: latest version
		deactivate Git(local)
		activate pg_landmetrics

   loop while user edits
	pg_landmetrics ->> pg_landmetrics: edit
	pg_landmetrics ->> Git(local): commit changes
		activate Git(local)
	Git(local)-->> pg_landmetrics: hash
		deactivate pg_landmetrics
   end

	Git(local)->> Rep. User(GitHub): git push
		deactivate pg_landmetrics
